name: Github Actions - Auto after CI

on:
    workflow_run:
        workflows: ["Node CI"]
        branches: [develop]
        types:
            - completed

jobs:
    merge:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: release
            - run: git branch
            - run: git fetch --all
            - run: git merge develop
